---

- name: "Install zabbix-agent package (FreeBSD)"
  pkgng: name=zabbix{{ zabbix_short_version }}-agent  state={{ zabbix_agent_package_state }}

- name: "create zabbix agent logdir (FreeBSD)"
  file: path={{ agent_logfile | dirname }} state=directory owner={{ zabbix_agent_user }} group={{ zabbix_agent_group }} mode=0755

- name: "Create zaiibx agent pid folder (FreeBSD)"
  file: path={{ agent_pidfile | dirname }} state=directory owner={{ zabbix_agent_user }} group={{ zabbix_agent_group }} mode=0755
